version: '3.8'

networks:
    nificluster:
      name: nificluster
      driver: bridge


services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 81:81
      - 82:82
    volumes:
      - ./nginx:/etc/nginx/conf.d/:Z
    networks:
      - nificluster
    depends_on:
      - nifi1
      - nifi2
      - nifi3

  zookeeper1:
    hostname: zookeeper1
    image: zookeeper:3.6.2
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    networks:
      - nificluster

  zookeeper2:
    hostname: zookeeper2
    image: zookeeper:3.6.2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    networks:
      - nificluster

  zookeeper3:
    hostname: zookeeper3
    image: zookeeper:3.6.2
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    networks:
      - nificluster

  nifi1:
    image: apache/nifi:latest
    hostname: nifi1
    ports:
      - 8080:8080
    user: root
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
      NIFI_CLUSTER_ADDRESS: nifi1
      NIFI_WEB_HTTP_PORT: 8080
    env_file:
      - ./nifi.config.global.env
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - nificluster

  nifi2:
    image: apache/nifi:latest
    hostname: nifi2
    ports:
      - 8081:8081
    user: root
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,address=7000,server=y,suspend=n
      NIFI_CLUSTER_ADDRESS: nifi2
      NIFI_WEB_HTTP_PORT: 8081
    env_file:
      - ./nifi.config.global.env
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - nificluster

  nifi3:
    image: apache/nifi:latest
    hostname: nifi3
    ports:
      - 8082:8082
    user: root
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,address=7000,server=y,suspend=n
      NIFI_CLUSTER_ADDRESS: nifi3
      NIFI_WEB_HTTP_PORT: 8082
    env_file:
      - ./nifi.config.global.env
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - nificluster
      

